source 'https://rubygems.org'

gem 'rails',          '4.1.0'
gem 'mysql2'
gem 'sass-rails',     '~> 4.0.3'
gem 'bootstrap-sass', '~> 3.1.1.0'
gem 'uglifier',       '>= 1.3.0'
gem 'coffee-rails',   '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder',       '~> 2.0'
gem 'sdoc',           '~> 0.4.0', group: :doc

gem 'spring', group: :development

group :test, :development do
  gem 'simplecov', require: false
end

group :test do
  gem 'rspec-rails',        '~> 2.14.2'
  gem 'cucumber-rails',     '= 1.4.0', :require => false
  gem 'capybara',           '= 2.2.1'
  gem 'poltergeist',        '= 1.5.0'
  gem 'database_cleaner',   '~> 1.2.0'
  gem 'factory_girl_rails', '~> 4.4.1'
end
