source 'http://rubygems.org'

gem 'rspec',    '>= 2.9.0'
gem 'simplecov' 
gem 'sqlite3',  '>= 1.3.5'

# bundler (1.1.3)
# diff-lcs (1.1.3)
# rake (0.8.7)
# rspec (2.9.0)
# rspec-core (2.9.0)
# rspec-expectations (2.9.0)
# rspec-mocks (2.9.0)
# sqlite3 (1.3.5) 
