source 'https://rubygems.org'

ruby '2.1.1'

gem 'rails',    '4.0.4'
gem 'oauth',    '~> 0.4.7'     # Library for both OAuth clients and servers
gem 'unicorn',  '4.8.2'        # Use unicorn as the app server
gem 'pg'                       # Use postgresql as the database for Active Record
gem 'sass-rails', '~> 4.0.2'   # Use SCSS for stylesheets
gem 'uglifier', '>= 1.3.0'     # Use Uglifier as compressor for JavaScript assets
gem 'coffee-rails', '~> 4.0.0' # Use CoffeeScript for .js.coffee assets and views
#gem 'jquery-rails'             # Use jquery as the primary JavaScript library
#gem 'turbolinks'
gem 'jbuilder', '~> 1.2'       # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'rails_12factor'           # For Heroku

# gem 'bcrypt', '~> 3.1.7'     # Use ActiveModel has_secure_password

group :development do
  gem 'foreman'                # To start the app via the Procfile
end

group :test, :development do
  gem 'simplecov', require: false  # Code-Coverage reporting
end

group :test do
  gem 'minitest-rails',     '= 0.9.2'
  gem 'minitest-reporters', '= 0.14.24'
  gem 'cucumber-rails',     '= 1.4.0', :require => false
  gem 'capybara',           '= 2.2.1'
  gem 'poltergeist',        '= 1.5.0'
  gem 'database_cleaner',   '= 1.2.0'
  gem 'factory_girl_rails', '= 4.4.0'
end
